def save():
    tk=open("nkm.txt","a")
    tk.write(f"\nname of student-{e1.get()}")
    tk.write(f"\nemail-{e3.get()}")
    tk.write(f"\nphone number-{str(e3.get())}")
    tk.close()
import tkinter as t
win=t.Tk()
win.configure(bg="skyblue")
l1=t.Label(win,text="Enter Data",bg="gray")
l1.grid(row=0,column=4)
l2=t.Label(win,text="Enter your name",bg="lightblue")
l2.grid(row=1,column=3)
l3=t.Label(win,text="enter your email ",bg="lightblue")           
l3.grid(row=2,column=3)
l4=t.Label(win,text="enter the phone number",bg="lightblue")
l4.grid(row=3,column=3)
l5=t.Label(win,text="select the course-",bg="lightblue")
l5.grid(row=4,column=3)
e1=t.Entry(win)
e1.grid(row=1,column=5)
e2=t.Entry(win)
e2.grid(row=2,column=5)
e3=t.Entry(win)
e3.grid(row=3,column=5)
drop= t.OptionMenu(win,"C++","Python","Java")
drop.grid(row=4,column=5)
button = t.Button(win,text="Submit Data",command=save,width="10",height="2")
button.grid(row=6,column=4)
